#!/bin/bash

# Capacitor iOS Development Setup Script
# This script helps configure your environment for local development

set -e

echo "🚀 EzeeRefer DX - Capacitor iOS Development Setup"
echo "=================================================="
echo ""

# Get Mac's IP address
echo "📡 Detecting your Mac's IP address..."
MAC_IP=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo "")

if [ -z "$MAC_IP" ]; then
    echo "⚠️  Could not auto-detect IP address."
    echo "Please find your Mac's IP manually:"
    echo "   System Settings > Network > Wi-Fi > Details > TCP/IP"
    echo ""
    read -p "Enter your Mac's IP address: " MAC_IP
else
    echo "✅ Detected IP: $MAC_IP"
    echo ""
    read -p "Is this correct? (y/n): " confirm
    if [ "$confirm" != "y" ]; then
        read -p "Enter your Mac's IP address: " MAC_IP
    fi
fi

# Create .env.local file
echo ""
echo "📝 Creating .env.local configuration..."
cat > .env.local << EOF
# Local Development Configuration
# Auto-generated by setup-capacitor-dev.sh

VITE_API_URL=http://$MAC_IP:8000

# Alternative: Use production server
# VITE_API_URL=http://65.0.132.181:8000
EOF

echo "✅ Created .env.local with API URL: http://$MAC_IP:8000"
echo ""

# Build the app
echo "🔨 Building the app..."
npm run build

echo ""
echo "📱 Syncing with iOS..."
npx cap sync ios

echo ""
echo "✅ Setup complete!"
echo ""
echo "📋 Next steps:"
echo "1. Start your backend server:"
echo "   cd ../backend"
echo "   python manage.py runserver 0.0.0.0:8000"
echo ""
echo "2. Open Xcode and run the app:"
echo "   npx cap open ios"
echo ""
echo "3. For Proxyman integration:"
echo "   - Open Proxyman"
echo "   - Go to Certificate > Install Certificate on iOS > Simulator"
echo ""
echo "4. View logs in Safari Web Inspector:"
echo "   - Safari > Develop > Simulator > EzHealth"
echo ""
echo "📖 For detailed troubleshooting, see CAPACITOR_API_DEBUGGING.md"
echo ""
